### ISSUE TITLE
IndentationError - jaeles-burp.py

### ISSUE THREAD

**Issue by uBadRequest** [jaeles-project/jaeles-plugins#1]
Hello,

I'm using Jython2.7.1, tried 2.7.0 and same error... I can't figure out how to fix it
```
IndentationError: ('unindent does not match any outer indentation level', ('/root/jaeles/jaeles-plugins/jaeles-burp.py', 246, 4, '    def saveToken(self, e):\n'))

	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:93)
	at org.python.core.ParserFacade.parse(ParserFacade.java:190)
	at org.python.core.Py.compile_flags(Py.java:2185)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:527)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.ac1.<init>(Unknown Source)
	at burp.m.a(Unknown Source)
	at burp.ey9.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by j3ssie** [comment]
This should be fixed with the latest commit. Please test it out and let me know if you still have an issue with it .
